export const data = [
  {
    id: 1,
    name: 'Tech Innovators Inc.',
    address: 'ул. Прогресса, д. 12, Москва, Россия',
  },
  {
    id: 2,
    name: 'Green Energy Solutions',
    address: 'ул. Энергетиков, д. 5, Санкт-Петербург, Россия',
  },
  {
    id: 3,
    name: 'HealthFirst Medical',
    address: 'ул. Здоровья, д. 8, Казань, Россия',
  },
  {
    id: 4,
    name: 'EduFuture Academy',
    address: 'ул. Образования, д. 3, Новосибирск, Россия',
  },
  {
    id: 5,
    name: 'SmartHome Technologies',
    address: 'ул. Умных Домов, д. 10, Екатеринбург, Россия',
  },
  {
    id: 6,
    name: 'FinTech Solutions',
    address: 'ул. Финансов, д. 14, Москва, Россия',
  },
  {
    id: 7,
    name: 'BioLife Sciences',
    address: 'ул. Биологов, д. 22, Санкт-Петербург, Россия',
  },
  {
    id: 8,
    name: 'AutoDrive Innovations',
    address: 'ул. Автомобилистов, д. 9, Казань, Россия',
  },
  {
    id: 9,
    name: 'AeroSpace Dynamics',
    address: 'ул. Космонавтов, д. 7, Новосибирск, Россия',
  },
  {
    id: 10,
    name: 'AgriTech Farms',
    address: 'ул. Сельхозтехники, д. 11, Екатеринбург, Россия',
  },
  {
    id: 11,
    name: 'CyberSecurity Experts',
    address: 'ул. Защиты, д. 16, Москва, Россия',
  },
  {
    id: 12,
    name: 'NanoTech Innovations',
    address: 'ул. Нанотехнологий, д. 4, Санкт-Петербург, Россия',
  },
  {
    id: 13,
    name: 'MedCare Solutions',
    address: 'ул. Медиков, д. 18, Казань, Россия',
  },
  {
    id: 14,
    name: 'EduTech Future',
    address: 'ул. Образования, д. 20, Новосибирск, Россия',
  },
  {
    id: 15,
    name: 'SmartCity Developments',
    address: 'ул. Умных Городов, д. 6, Екатеринбург, Россия',
  },
  {
    id: 16,
    name: 'EcoFriendly Products',
    address: 'ул. Экологов, д. 13, Москва, Россия',
  },
  {
    id: 17,
    name: 'GreenTech Innovations',
    address: 'ул. Зелёных Технологий, д. 8, Санкт-Петербург, Россия',
  },
  {
    id: 18,
    name: 'HealthTech Solutions',
    address: 'ул. Здоровья, д. 15, Казань, Россия',
  },
  {
    id: 19,
    name: 'FutureEdu Academy',
    address: 'ул. Будущего, д. 12, Новосибирск, Россия',
  },
  {
    id: 20,
    name: 'SmartGrid Technologies',
    address: 'ул. Энергосетей, д. 3, Екатеринбург, Россия',
  },
  {
    id: 21,
    name: 'TechPioneers Inc.',
    address: 'ул. Пионеров, д. 17, Москва, Россия',
  },
  {
    id: 22,
    name: 'GreenEnergy Solutions',
    address: 'ул. Энергетиков, д. 5, Санкт-Петербург, Россия',
  },
  {
    id: 23,
    name: 'LifeSciences Bio',
    address: 'ул. Биологов, д. 19, Казань, Россия',
  },
  {
    id: 24,
    name: 'EduTech Academy',
    address: 'ул. Образования, д. 1, Новосибирск, Россия',
  },
  {
    id: 25,
    name: 'HomeTech Innovations',
    address: 'ул. Умных Домов, д. 10, Екатеринбург, Россия',
  },
  {
    id: 26,
    name: 'FinTech Pioneers',
    address: 'ул. Финансов, д. 20, Москва, Россия',
  },
  {
    id: 27,
    name: 'BioLife Innovations',
    address: 'ул. Биологов, д. 22, Санкт-Петербург, Россия',
  },
  {
    id: 28,
    name: 'AutoTech Drive',
    address: 'ул. Автомобилистов, д. 9, Казань, Россия',
  },
  {
    id: 29,
    name: 'AeroDynamics Space',
    address: 'ул. Космонавтов, д. 7, Новосибирск, Россия',
  },
  {
    id: 30,
    name: 'AgriFarms Tech',
    address: 'ул. Сельхозтехники, д. 11, Екатеринбург, Россия',
  },
  {
    id: 31,
    name: 'CyberExperts Security',
    address: 'ул. Защиты, д. 16, Москва, Россия',
  },
  {
    id: 32,
    name: 'NanoInnovations Tech',
    address: 'ул. Нанотехнологий, д. 4, Санкт-Петербург, Россия',
  },
  {
    id: 33,
    name: 'MedSolutions Care',
    address: 'ул. Медиков, д. 18, Казань, Россия',
  },
  {
    id: 34,
    name: 'FutureEdu Tech',
    address: 'ул. Образования, д. 20, Новосибирск, Россия',
  },
  {
    id: 35,
    name: 'SmartDevelopments City',
    address: 'ул. Умных Городов, д. 6, Екатеринбург, Россия',
  },
];

export const newData = [
  {
    id: 36,
    name: 'Tech Innovators Inc.',
    address: 'ул. Прогресса, д. 12, Москва, Россия',
  },
  {
    id: 37,
    name: 'Green Energy Solutions',
    address: 'ул. Энергетиков, д. 5, Санкт-Петербург, Россия',
  },
  {
    id: 38,
    name: 'HealthFirst Medical',
    address: 'ул. Здоровья, д. 8, Казань, Россия',
  },
  {
    id: 39,
    name: 'EduFuture Academy',
    address: 'ул. Образования, д. 3, Новосибирск, Россия',
  },
  {
    id: 40,
    name: 'SmartHome Technologies',
    address: 'ул. Умных Домов, д. 10, Екатеринбург, Россия',
  },
  {
    id: 41,
    name: 'FinTech Solutions',
    address: 'ул. Финансов, д. 14, Москва, Россия',
  },
  {
    id: 42,
    name: 'BioLife Sciences',
    address: 'ул. Биологов, д. 22, Санкт-Петербург, Россия',
  },
  {
    id: 43,
    name: 'AutoDrive Innovations',
    address: 'ул. Автомобилистов, д. 9, Казань, Россия',
  },
  {
    id: 44,
    name: 'AeroSpace Dynamics',
    address: 'ул. Космонавтов, д. 7, Новосибирск, Россия',
  },
  {
    id: 45,
    name: 'AgriTech Farms',
    address: 'ул. Сельхозтехники, д. 11, Екатеринбург, Россия',
  },
  {
    id: 46,
    name: 'CyberSecurity Experts',
    address: 'ул. Защиты, д. 16, Москва, Россия',
  },
  {
    id: 47,
    name: 'NanoTech Innovations',
    address: 'ул. Нанотехнологий, д. 4, Санкт-Петербург, Россия',
  },
  {
    id: 48,
    name: 'MedCare Solutions',
    address: 'ул. Медиков, д. 18, Казань, Россия',
  },
  {
    id: 49,
    name: 'EduTech Future',
    address: 'ул. Образования, д. 20, Новосибирск, Россия',
  },
  {
    id: 50,
    name: 'SmartCity Developments',
    address: 'ул. Умных Городов, д. 6, Екатеринбург, Россия',
  },
];

export const mockEmployees = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    position: 'Software Engineer',
    companyId: 1,
  },
  { id: 2, firstName: 'Jane', lastName: 'Smith', position: 'Software Engineer', companyId: 1 },
  { id: 3, firstName: 'Michael', lastName: 'Johnson', position: 'Software Engineer', companyId: 1 },
  { id: 4, firstName: 'Emily', lastName: 'Brown', position: 'Software Engineer', companyId: 1 },
  { id: 5, firstName: 'Chris', lastName: 'Davis', position: 'Software Engineer', companyId: 1 },
  { id: 6, firstName: 'Jessica', lastName: 'Miller', position: 'Software Engineer', companyId: 1 },
  { id: 7, firstName: 'David', lastName: 'Wilson', position: 'Software Engineer', companyId: 1 },
  { id: 8, firstName: 'Ashley', lastName: 'Moore', position: 'Software Engineer', companyId: 1 },
  { id: 9, firstName: 'Daniel', lastName: 'Taylor', position: 'Software Engineer', companyId: 1 },
  { id: 10, firstName: 'Sarah', lastName: 'Anderson', position: 'Software Engineer', companyId: 1 },
  { id: 11, firstName: 'Matthew', lastName: 'Thomas', position: 'Software Engineer', companyId: 1 },
  { id: 12, firstName: 'Laura', lastName: 'Jackson', position: 'Software Engineer', companyId: 1 },
  { id: 13, firstName: 'Joshua', lastName: 'White', position: 'Software Engineer', companyId: 1 },
  { id: 14, firstName: 'Megan', lastName: 'Harris', position: 'Software Engineer', companyId: 1 },
  { id: 15, firstName: 'Andrew', lastName: 'Martin', position: 'Software Engineer', companyId: 1 },
  {
    id: 16,
    firstName: 'Hannah',
    lastName: 'Thompson',
    position: 'Software Engineer',
    companyId: 1,
  },
  {
    id: 17,
    firstName: 'Alexander',
    lastName: 'Garcia',
    position: 'Software Engineer',
    companyId: 1,
  },
  {
    id: 18,
    firstName: 'Samantha',
    lastName: 'Martinez',
    position: 'Software Engineer',
    companyId: 1,
  },
  { id: 19, firstName: 'Ryan', lastName: 'Robinson', position: 'Software Engineer', companyId: 1 },
  { id: 20, firstName: 'Olivia', lastName: 'Clark', position: 'Software Engineer', companyId: 1 },
  {
    id: 21,
    firstName: 'Brandon',
    lastName: 'Rodriguez',
    position: 'Software Engineer',
    companyId: 1,
  },
  { id: 22, firstName: 'Sophia', lastName: 'Lewis', position: 'Software Engineer', companyId: 1 },
  { id: 23, firstName: 'Tyler', lastName: 'Lee', position: 'Software Engineer', companyId: 1 },
  { id: 24, firstName: 'Alyssa', lastName: 'Walker', position: 'Software Engineer', companyId: 1 },
  { id: 25, firstName: 'Nicholas', lastName: 'Hall', position: 'Software Engineer', companyId: 1 },
  { id: 26, firstName: 'Brittany', lastName: 'Allen', position: 'Software Engineer', companyId: 1 },
  { id: 27, firstName: 'Zachary', lastName: 'Young', position: 'Software Engineer', companyId: 1 },
  {
    id: 28,
    firstName: 'Rachel',
    lastName: 'Hernandez',
    position: 'Software Engineer',
    companyId: 1,
  },
  { id: 29, firstName: 'Ethan', lastName: 'King', position: 'Software Engineer', companyId: 1 },
  {
    id: 30,
    firstName: 'Victoria',
    lastName: 'Wright',
    position: 'Software Engineer',
    companyId: 1,
  },
  { id: 31, firstName: 'Justin', lastName: 'Lopez', position: 'Software Engineer', companyId: 1 },
  { id: 32, firstName: 'Natalie', lastName: 'Hill', position: 'Software Engineer', companyId: 1 },
  { id: 33, firstName: 'Kevin', lastName: 'Scott', position: 'Software Engineer', companyId: 1 },
  { id: 34, firstName: 'Lauren', lastName: 'Green', position: 'Software Engineer', companyId: 1 },
  { id: 35, firstName: 'Jason', lastName: 'Adams', position: 'Software Engineer', companyId: 1 },

  {
    id: 36,
    firstName: 'Jane',
    lastName: 'Smith',
    position: 'Product Manager',
    companyId: 1,
  },
  {
    id: 37,
    firstName: 'Alice',
    lastName: 'Johnson',
    position: 'UX Designer',
    companyId: 2,
  },
  {
    id: 38,
    firstName: 'Bob',
    lastName: 'Brown',
    position: 'DevOps Engineer',
    companyId: 2,
  },
  {
    id: 39,
    firstName: 'Charlie',
    lastName: 'Davis',
    position: 'QA Engineer',
    companyId: 3,
  },
  {
    id: 40,
    firstName: 'Diana',
    lastName: 'Evans',
    position: 'Data Scientist',
    companyId: 3,
  },
];

export const newEmployees = [
  { id: 41, firstName: 'Paul', lastName: 'Baker', position: 'Software Engineer', companyId: 1 },
  { id: 42, firstName: 'Emma', lastName: 'Gonzalez', position: 'Software Engineer', companyId: 1 },
  {
    id: 43,
    firstName: 'Benjamin',
    lastName: 'Nelson',
    position: 'Software Engineer',
    companyId: 1,
  },
  { id: 44, firstName: 'Grace', lastName: 'Carter', position: 'Software Engineer', companyId: 1 },
  { id: 45, firstName: 'Jack', lastName: 'Mitchell', position: 'Software Engineer', companyId: 1 },
  { id: 46, firstName: 'Chloe', lastName: 'Perez', position: 'Software Engineer', companyId: 1 },
  { id: 47, firstName: 'Lucas', lastName: 'Roberts', position: 'Software Engineer', companyId: 1 },
  { id: 48, firstName: 'Ella', lastName: 'Turner', position: 'Software Engineer', companyId: 1 },
  { id: 49, firstName: 'Isaac', lastName: 'Phillips', position: 'Software Engineer', companyId: 1 },
  { id: 50, firstName: 'Mia', lastName: 'Campbell', position: 'Software Engineer', companyId: 1 },
  { id: 51, firstName: 'Nathan', lastName: 'Parker', position: 'Software Engineer', companyId: 1 },
  { id: 52, firstName: 'Lily', lastName: 'Evans', position: 'Software Engineer', companyId: 1 },
  { id: 53, firstName: 'Henry', lastName: 'Edwards', position: 'Software Engineer', companyId: 1 },
  { id: 54, firstName: 'Zoe', lastName: 'Collins', position: 'Software Engineer', companyId: 1 },
  { id: 55, firstName: 'Aaron', lastName: 'Stewart', position: 'Software Engineer', companyId: 1 },
  { id: 56, firstName: 'Amelia', lastName: 'Sanchez', position: 'Software Engineer', companyId: 1 },
  { id: 57, firstName: 'Evan', lastName: 'Morris', position: 'Software Engineer', companyId: 1 },
  { id: 58, firstName: 'Madison', lastName: 'Rogers', position: 'Software Engineer', companyId: 1 },
  { id: 59, firstName: 'Adam', lastName: 'Reed', position: 'Software Engineer', companyId: 1 },
  { id: 60, firstName: 'Ava', lastName: 'Cook', position: 'Software Engineer', companyId: 1 },
];
